name: Assign To Me Action

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]

jobs:
  assign:
    # If the acton was triggered by a new comment that starts with `/assign-to-me`
    # or a on a schedule
    if: >
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/assign-to-me')) ||
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assign the user or unassign stale assignments
        uses: ./
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          required_label: good-first-issue
          assigned_label: Is-Assigned
